# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Junhong Chen"
description              : "AI in Health and Medicine"
repository               : "chenjh356/chenjh356.github.io"
google_scholar_stats_use_cdn : false

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification : 0mowx_-wj9DfY-NBbL1U39vTZVaLUWCCsvexUSzpIA8 # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   : 304AB024627AD3A1DDBAA1B34DCD29A8 # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Junhong Chen"
  avatar           : "images/avatar.jpeg"
  bio              : "Sun Yat-sen University"
  location         : "Shenzhen, China"
  employer         : "BGI Research"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=jqslgHAAAAAJ"
  email            : "chenjh356@mail2.sysu.edu.cn"
  researchgate     : "https://www.researchgate.net/profile/Junhong-Chen-10"
  uri              : 
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "chenjh356"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : # e.g., "linkedin username"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : "https://orcid.org/0000-0002-8313-8317"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

education:
  - degree: "BMed"
    major: "Preventive Medicine"
    institution: "Sun Yat-sen University(SYSU)"
    time: "Sep. 2018 - Jun. 2023"
    location: "Guangzhou, China"
    img: "images/SYSU.png"

publications:
  - title: "Unraveling the impact of host genetics and factors on the urinary microbiome in a young population."
    authors: 
      - "Leying Zou"
      - "Zhe Zhang"
      - "Junhong Chen"
      - "Ruijin Guo"
      - "Xin Tong"
      - "Yanmei Ju"
      - "Haorong Lu"
      - "Huanming Yang"
      - "Jian Wang"
      - "Yang Zong"
      - "Xun Xu"
      - "Xin Jin"
      - "Liang Xiao"
      - "Huijue Jia"
      - "Tao Zhang"
      - "Xiaomin Liu"
    journal: "mBio"
    year: "2024"
    img: "images/urine.png"
    position: "Co-First"
    html: "https://journals.asm.org/doi/10.1128/mbio.02773-24"
    pdf: "/pdf/TangJ-2022-Mechanism%20of%20Magnetic%20Flux%20Leakage%20Detection%20Method%20Based%20on%20the%20Slotted.pdf"
    other: "2024: e02773-24"
    JCR: "Q1"
    IF: "5.9"
  
  - title: "Deep Learning Assisted Classification of T1œÅ-MR Based Intervertebral Disc Degeneration Phases."
    authors: [Yanrun Li, Meiyu Hu, Junhong Chen, Zemin Ling, Xuenong Zou, Wuteng Cao, Fuxin Wei]
    journal: "JMRI"
    year: "2024"
    img: "images/jmri29499.png"
    position: "Co-First"
    html: "https://onlinelibrary.wiley.com/doi/10.1002/jmri.29499"
    pdf: "/pdf/TangJ-2022-Mechanism%20of%20Magnetic%20Flux%20Leakage%20Detection%20Method%20Based%20on%20the%20Slotted.pdf"
    other: "2024"
    JCR: "Q1"
    IF: "4.4"

  - title: "A novel method for the detection of ferromagnetic materials based on the magnetic flux leakage."
    authors: 
      - "Junhong Chen"
      - "Yong Zhang"
      - "XYZ"
      - "ZZ"
    journal: "Sensors"
    year: "2021"
    img:
    position: "First Author"
    html: "https://www.mdpi.com/1424-8220/21/1/1"
    pdf: "/pdf/TangJ-2022-A%20Novel%20Method%20for%20the%20Detection%20of%20Ferromagnetic%20Materials%20Based%20on%20the%20Magnetic%20Flux%20Leakage.pdf"
    other: "2022, 22(9): 3587."
    JCR: "Q1"
    IF: "5.705"
# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
